import { defineConfig } from "drizzle-kit";

export default defineConfig({
  schema: "./src/lib/server/schema.ts",
  dialect: "sqlite",
  out: "./drizzle",
  dbCredentials: {
    // Pointing to the local replica database generated by wrangler
    url: ".wrangler/state/v3/d1/miniflare-D1DatabaseObject/7343f15b1b7a2bd98f4fe20d6dcad6e6cfc3f9ee38e360c38b8ec4370c9f1fa3.sqlite",
  },
});
