name = "ananas"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-10-24"

[site]
bucket = ".svelte-kit/cloudflare"

[build]
command = "bun run build"

[[kv_namespaces]]
binding = "ananas_email_addresses"
id = "41c5ef950aa242f29f4b9b049f637ae5"

pages_build_output_dir = ".svelte-kit/cloudflare"
